name: Appium Testing
run-name: workflow of Appium Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  appium-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Local Appium Excel Reports
        uses: actions/upload-artifact@v4
        with:
          name: appium-test-reports
          path: |
            appium_tests/reports/*.xlsx
            appium_tests/*.xlsx
